# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install pytest requests

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV OPENAI_API_TOKEN="sk-PLEASE-PROVIDEE-YOUR-OWN-API-TOKEN"

# Run main.py when the container launches with Gunicorn and set the timeout to 120 seconds
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "--timeout", "120", "model:app"]
